configName: sam_a5d27_som1_ek_freertos
folderName: sam_a5d27_som1_ek_freertos
format_version: v1.0
frameworkPath: ..\..\..
processor: ATSAMA5D27CD1G
projectName: hid_basic_mouse_usart_sam_a5d27_som1_ek_freertos
settings:
  PackageFilter: audio;bsp;core;core_apps_sam_9x60;core_apps_sam_a5d2;csp;csp_apps_pic32cm_le_ls;csp_apps_sam_9x60;usb;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMA5D2_DFP\1.5.42\atdf\ATSAMA5D27CD1G.atdf
