configName: sam_e70_xult
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: ATSAME70Q21B
projectName: ''
settings:
  PackageFilter: bsp;core;csp;quick_docs;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: SAME70_DFP\4.10.248
