configName: sam_g55_xpro
folderName: t
format_version: v1.0
frameworkPath: ../../..
processor: ATSAMG55J19
projectName: c:\jcb\__tt
settings:
  PackageFilter: bsp;core;csp;quick_docs;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: SAMG_DFP\3.8.197
