configName: pic32mz_ef_sk
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: PIC32MZ2048EFH144
projectName: ''
settings:
  PackageFilter: bsp;core;core_apps_sam_9x60;core_apps_sam_a7g5;csp;Devices;dev_packs;quick_docs;usb;usb_apps_device;usb_apps_dual_role;usb_apps_host;usb_apps_multi_controller
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: PIC32MZ-EF_DFP\1.4.168
