format_version: v1.0
type: UniqueComponent
attributes: {id: drv_usbhs_v1}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: USB_DRV_HOST_EHCI_PORTS_SELECTION}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0x06'}
  - type: String
    attributes: {id: USB_DRV_HOST_OHCI_PORTS_SELECTION}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0x06'}
- type: ElementPosition
  attributes: {x: '3', y: '236', id: drv_usbhs_v1}
