format_version: v1.0
type: UniqueComponent
attributes: {id: BSP_SAM_A5D2_Xplained_Ultra, bsp: 'true'}
children:
- type: ElementPosition
  attributes: {x: '151', y: '63', id: BSP_SAM_A5D2_Xplained_Ultra}
