configName: sam_g55_xpro
folderName: sam_g55_xpro
format_version: v1.0
frameworkPath: ..\..\..
processor: ATSAMG55J19
projectName: hub_cdc_hid_sam_g55_xpro
settings:
  PackageFilter: bsp;core;core_apps_sam_9x60;core_apps_sam_a7g5;csp;Devices;dev_packs;quick_docs;usb;usb_apps_device;usb_apps_dual_role;usb_apps_host;usb_apps_multi_controller
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: SAMG_DFP\3.8.197
